### ISSUE TITLE
Error while installing pm2

### ISSUE THREAD

**Issue by venkateshk111** [aws-samples/aws-three-tier-web-architecture-workshop#1]
Section: [Part 3: App Tier Instance Deployment](https://catalog.us-east-1.prod.workshops.aws/workshops/85cd2bb2-7f79-4e96-bdee-8078e469752a/en-US/part3)
[Configure App Instance](https://catalog.us-east-1.prod.workshops.aws/workshops/85cd2bb2-7f79-4e96-bdee-8078e469752a/en-US/part3/configureinstance)

Step 5: 
PM2 is a daemon process manager that will keep our node.js app running when we exit the instance or if it is rebooted. Install that as well.
```
1 npm install -g pm2
```   

When above command is run on Amazon Linux 2 getting below error

```
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

**Comment by awsshivs** [comment]
Thank you for pointing the bug out. 
This is currently happening with the latest version of node (18), so please use `nvm install 16` to use the latest LTS node version. PM2 install should work with that. 
I'll be updating the workshop instructions soon.

**Comment by awsshivs** [comment]
Alright, i've released updated workshop instructions:https://catalog.us-east-1.prod.workshops.aws/workshops/85cd2bb2-7f79-4e96-bdee-8078e469752a/en-US

closing this!
